name: Partial configuration export
type: module
description: 'Partial export of modified configuration files'
package: Development
# version: 8.x-1.0-dev
# core: 8.x
dependencies:
  - config
tags:
  - developer
# Information added by Drupal.org packaging script on 2016-12-18
version: '8.x-1.4'
core: '8.x'
project: 'config_partial_export'
datestamp: 1482080287
